### ISSUE TITLE
NPM Authentication check fails after v5.3.1 -> v5.3.2 upgrade

### ISSUE THREAD

**Issue by tripodsan** [semantic-release/npm#214]
Note: this issue is solved, but it might be help others to find a solution in case they run into the same problems.

---

After we updated semantic release to 15.13.28 (which includes semantic-release/npm v5.3.2) we see errors in our CI:

```
[10:53:02] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[10:53:02] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
```

we had a step in our ci script that writes the `.npmrc`:

```
   - run:
        name: configure npm registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

    - run:
        name: Semantic Release
        command: npm run semantic-release
```

The solution was to remove the `configure npm registry` step, since the `NPM_TOKEN` environment variable is automatically used in semantic-release/npm. 

However, it is not totally clear to me, which this broke.
