### ISSUE TITLE
Using @semantic-release/npm with Nexus private repository

### ISSUE THREAD

**Issue by bedoro** [semantic-release/npm#279]
Hello there!

I am using a private npm repository using Sonatype Nexus to publish packages to using semantic-release.

In Nexus, the `latest` dist-tag is implemented in a weird way. Nexus does not allow updating it using `npm dist-tag add`/`npm dist-tag rm`. As far as I understand, Nexus sets the latest tag to the last published version that does not have another tag (like `next`).
Related issue [here](https://issues.sonatype.org/browse/NEXUS-22915). 

Since `@semantic-release/npm` calls `npm dist-tag add`, the publishing process fails because Nexus sends back an HTTP Error `400 Bad Request`:
```
[semantic-release] [@semantic-release/npm] › ℹ  Adding version 1.0.0 to npm registry on dist-tag latest

npm ERR! code E400

npm ERR! 400 Bad Request - PUT http://nexus/repository/repo/-/package/my-package/dist-tags/latest - Unable to update latest tag
```

Is there any way to skip the `npm dist-tag add` command, preferably only on master branch? 
Maybe there's even a better solution? I surely can't be the first to publish to Nexus using semantic-release... 💯

**Comment by kaerbr** [comment]
Hi @bedoro ,

I ran in a somewhat similar issue:
We have a nexus too. But we have two seperate repositories for "releases" and "snapshots".

So i had to set `npmPublish: false` and after that I wrote a custom publish script to publish accordingly.

.releaserc.yml:
```
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - publishCmd: $CI_PROJECT_DIR/publish.sh ${nextRelease.version}
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
  - "@semantic-release/gitlab"
  # As discussed in this issue: https://github.com/semantic-release/semantic-release/issues/1603 there is no support for GitFlow.
  # If we would like to stick to kinda GitFlow (with prerelease/develop), we will have to use this community plugin or merge back by ourselves.
  - - "@saithodev/semantic-release-backmerge"
    - branches:
        - from: main
          to: prerelease
branches:
  - main
  - "[0-9]+.[0-9]+.x"
  - name: prerelease
    prerelease: rc
```

publish.sh:
```
#!/bin/sh

if echo "$1" | grep -q "rc"
then
  npm run-script build:staging
  npm publish --registry=https://self.hosted/nexus/repository/npm-private-snapshots/ --strict-ssl=false --_auth=$NEXUS_ACCESS_TOKEN --access=restricted
else
  npm run-script build:prod
  npm publish --registry=https://self.hosted/nexus/repository/npm-private-releases/ --strict-ssl=false --_auth=$NEXUS_ACCESS_TOKEN --access=restricted
fi
```

I hope this kinda helps after nearly 2 years 😬
