### ISSUE TITLE
package version not getting updated when pkgRoot is set

### ISSUE THREAD

**Issue by wyardley** [semantic-release/npm#417]
(I have seen https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository and https://github.com/semantic-release/semantic-release/issues/1593, though I think the issue is different here)

With my initial config, without `pkgRoot` set to `dist` and without the assets specified, the git plugin was updating my `package.json` / `package-lock.json` in the release commit. Once I added it, it seems to not get updated anymore.

```yaml
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/npm"
    - pkgRoot: dist
  - "@semantic-release/git"
  - - "@semantic-release/github"
     - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
```

In the output (from the first config above), it seems like the package version is getting moved into pkgRoot, which probably explains why the git plugin isn't committing the updated file. I am guessing this may be safest to avoid unexpected behavior, but is there any way to commit the package / package-lock fix, either with the plugin, or maybe through some kind of exec step to copy the file back?

```
[10:20:10 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 0.14.1 to package.json in /home/circleci/project/dist
v0.14.1
[10:20:10 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[10:20:10 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[10:20:11 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[10:20:12 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v0.14.1
```

(note: I can see that this behavior is documented in https://github.com/semantic-release/npm/blob/f089d9dcc2163046138fb0c996b7cc8028327718/README.md though hadn't quite understood the implications).
