### ISSUE TITLE
You cannot publish over the previously published versions

### ISSUE THREAD

**Issue by oliveirarafa** [semantic-release/npm#518]
Guys, I'm now to using the semantic-release.

When I run my pipeline  i'm always getting a "npm verb stack HttpErrorGeneral: 403 Forbidden - PUT https://registry.npmjs.org/@govbr-ds%2fwebcomponents - You cannot publish over the previously published versions: 1.3.1.". This version wasn't published before.

Even with this error, my package get published on npmjs but my pipeline fails. What i'm doing wrong?

Am I trying to publish 2 times the same package? Where?

Here is my .releaserc.yml
```yml
---
# Documentação: https://semantic-release.gitbook.io/semantic-release/usage/configuration
branches:
  # Estável
  - main
  - '+([0-9])?(.{+([0-9]),x}).x'
  # Próximas versões
  - next
  - next-major
  # Prereleases
  # Formatos aceitáveis: 1.1.1-prefixo, 1.1.x-prefixo, 1.x.x-prefixo
  - name: '+([0-9])?(.{+([0-9]),x}).x-rc'
    prerelease: rc
  - name: '+([0-9])?(.{+([0-9]),x}).x-beta'
    prerelease: beta
  - name: '+([0-9])?(.{+([0-9]),x}).x-alpha'
    prerelease: alpha
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
      writerOpts:
        commitsSort:
          - subject
          - scope
  - - '@semantic-release/changelog'
  - - '@semantic-release/exec'
    - publishCmd: zip dist.zip dist/webcomponents.umd.min.js dist/webcomponents.umd.js dist/webcomponents.common.js
  - - '@semantic-release/gitlab'
    - assets:
        - path: dist.zip
          label: JS Distribution
        - path: README.md
          label: README
  - - semantic-release-discord
    - onSuccessTemplate:
        username: '$package_name'
        content: Disponibilizamos uma nova versão do nosso pacote $package_name! Mais detalhes estão disponíveis no site e repositório.
        embeds:
          - title: '$package_name $npm_package_version'
            url: '$repo_url'
            description: '$release_notes'
            color: 4486596
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
        - package.json
        - CHANGELOG.md
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
```

Thank you for anyones help.
